[[intro]]
== Introduction

=== Goals

The NetCDF library <<NetCDF>> is designed ...

=== Terminology

auxiliary coordinate variable::
Any netCDF variable that contains coordinate data...

boundary variable::
A boundary variable is associated with a ...

CDL syntax::
The ASCII format used to describe the ...

=== Overview

No variable or dimension names are standardized by this convention. Instead we follow the lead of the NUG and standardize only the names of attributes and some of the values taken by those attributes. The overview provided in this section will be followed with more complete descriptions in following sections.
<<appendix-attributes, Appendix A, Attributes>>
contains a summary of all the attributes used in this convention.

We recommend that the NUG defined attribute `Conventions` be given the string
value `"CF-1.6"` to identify datasets that conform to these conventions.

The general description of a file's contents should be contained in the
following attributes: title, history, institution, source, comment and
references
(<<Description of file contents, Section 2.6.2, "Description of file contents">>),
For backwards compatibility with COARDS none of these attributes is required, but their use is recommended to provide human readable documentation of the file contents.
