= NetCDF Climate and Forecast (CF) Metadata Conventions
CF People
:toc: macro

Original authors:: Brian, ...

Additional authors:: John, ...

<<Standard name table format>>

== Preface

Home page:: Contains links to: pervious draft and current ...
Revision history:: This document will be updated to reflect ...

== Table of contents

toc::[]

:numbered:

== Introduction

=== Goals

The NetCDF library <<NetCDF>> is designed ...

=== Terminology

auxiliary coordinate variable::
Any netCDF variable that contains coordinate data...

boundary variable::
A boundary variable is associated with a ...

CDL syntax::
The ASCII format used to describe the ...

=== Overview

No variable or ...
<<Attributes>> 
<<Attributes,Some attributes>>
<<Appendix A: Attributes>> 
<<Appendix A: Attributes,Some attributes>>
<<appendix-a-attributes>>
<<appendix-a-attributes,more attributes>>
contains a summary
of all the attributes used in this convention.

We recommend that the NUG defined attribute `Conventions` be given the string
value `"CF-1.6"` to identify datasets that conform to these conventions.


== NetCDF files and components

Blah ...

== Description of the data

=== Units

Blah blah ...

.Supported units
|===
|Factor|Prefix|Abbreviation| |Factor|Prefix|Abbreviation

|1e1|deca,deka|da| |1e-1|deci|d

|1e2|hecto|h| |1e-2|centi|c
|===

include::chapter4.adoc[]
*NB. This isn't very useful, as it doesn't turn up in the TOC.

:!numbered:

[appendix]
== Attributes

All CF attributes are listed here...

.Attributes
|===
|Factor|Prefix|Abbreviation| |Factor|Prefix|Abbreviation

|1e1|deca,deka|da| |1e-1|deci|d

|1e2|hecto|h| |1e-2|centi|c
|===

[appendix]
== Standard name table format

The CF standard name table is ...

[bibliography]
== Bibliography
- [[[COARDS]]] Conventions for the standardization [sic] ...
- [[[FGDC]]] Content standard for digital geospatial metadata.
- [[[NetCDF]]] NetCDF software package...
